import React from "react";

import { ScrollArea } from "orobas-utils";

import {
  accordionssRoute,
  alertDialogsRoute,
  alertsRoute,
  aspectRatioRoute,
  avatarsRoute,
  badgesRoute,
  buttonsRoute,
  calendarRoute,
  cardRoute,
  carouselRoute,
  checkboxRoute,
  collapsibleRoute,
  commandRoute,
  contextMenuRoute,
  datePickerRoute,
  dialogRoute,
  dropdownRoute,
  hoverCardRoute,
  inputRoute,
  labelRoute,
  menubarRoute,
  navigationMenuRoute,
  paginationRoute,
  popoverRoute,
  progressRoute,
  radioGroupRoute,
  resizableRoute,
  scrollAreaRoute,
  selectRoute,
  separatorRoute,
  sheetRoute,
  skeletonRoute,
  sliderRoute,
  sonnerRoute,
  switchRoute,
  tableRoute,
  tabsRoute,
  textareaRoute,
  toastRoute,
  toggleGroupRoute,
  toggleRoute,
  tooltipRoute,
} from "@/pages/Documentation";

import { SidebarItem } from "./SidebarItem";
import { SidebarItemGroup } from "./SidebarItemGroup";

export function DocumentationSidebar() {
  return (
    <ScrollArea>
      <SidebarItemGroup label="Primitives">
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Overview"}
          to={"/documentation"}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Aspect Ratio"}
          to={aspectRatioRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Accordion"}
          to={accordionssRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Alerts"}
          to={alertsRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Alert Dialogs"}
          to={alertDialogsRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Avatars"}
          to={avatarsRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Badges"}
          to={badgesRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Button"}
          to={buttonsRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Calendar"}
          to={calendarRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Card"}
          to={cardRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Carousel"}
          to={carouselRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Checkbox"}
          to={checkboxRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Collapsible"}
          to={collapsibleRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Command"}
          to={commandRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Context Menu"}
          to={contextMenuRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Date Picker"}
          to={datePickerRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Dialog"}
          to={dialogRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Dropdown"}
          to={dropdownRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Hover Card"}
          to={hoverCardRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Input"}
          to={inputRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Label"}
          to={labelRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Menubar"}
          to={menubarRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Navigation Menu"}
          to={navigationMenuRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Pagination"}
          to={paginationRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Popover"}
          to={popoverRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Progress"}
          to={progressRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Radio Group"}
          to={radioGroupRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Resizable"}
          to={resizableRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Scroll Area"}
          to={scrollAreaRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Select"}
          to={selectRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Separator"}
          to={separatorRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Sheet"}
          to={sheetRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Skeleton"}
          to={skeletonRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Slider"}
          to={sliderRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Sonner"}
          to={sonnerRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Switch"}
          to={switchRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Table"}
          to={tableRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Tabs"}
          to={tabsRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Textarea"}
          to={textareaRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Toast"}
          to={toastRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Toggle"}
          to={toggleRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Toggle Group"}
          to={toggleGroupRoute.to}
        />
        <SidebarItem
          icon="radix-icons:blending-mode"
          label={"Tooltip"}
          to={tooltipRoute.to}
        />
      </SidebarItemGroup>
    </ScrollArea>
  );
}
